---
kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - cd exporter
      - go build
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_apikey
      files: exporter/exporter
    when:
      event: tag
